config:
  target: 'http://host.docker.internal:9011'
  phases:
    - duration: 60
      arrivalRate: 1
      
      rampTo: 20
      name: "Ramp-up phase"
    - duration: 60
      arrivalRate: 20
      rampTo: 5
      name: "Ramp down phase"
    - duration: 60
      arrivalRate: 5
      rampTo: 20
      name: "Ramp up phase"
    - duration: 60
      arrivalRate: 20
      rampTo: 5
      name: "Ramp down phase"
    - duration: 60
      arrivalRate: 5
      rampTo: 20
      name: "Ramp up phase"

scenarios:
  - flow:
      - post:
          url: "/post"
          json: "{{ payload }}"

  payload: "{{ $processEnvironment.PAYLOAD_FILE }}"
