config:
  phases:
  - arrivalRate: 1
    duration: 5
    name: Ramp-up phase 1
    rampTo: 100
  - arrivalRate: 100
    duration: 5
    name: Ramp down phase 1
    rampTo: 5
  - arrivalRate: 5
    duration: 5
    name: Ramp-up phase 2
    rampTo: 100
  - arrivalRate: 100
    duration: 5
    name: Ramp down phase 2
    rampTo: 5
  - arrivalRate: 5
    duration: 5
    name: Ramp-up phase 3
    rampTo: 100
  - arrivalRate: 100
    duration: 5
    name: Ramp down phase 3
    rampTo: 5
  - arrivalRate: 5
    duration: 5
    name: Ramp-up phase 4
    rampTo: 100
  - arrivalRate: 100
    duration: 5
    name: Ramp down phase 4
    rampTo: 5
  - arrivalRate: 5
    duration: 5
    name: Ramp-up phase 5
    rampTo: 100
  target: http://172.17.0.2:9000
payload: '{{ $processEnvironment.PAYLOAD_FILE }}'
scenarios:
- flow:
  - post:
      json: '{{ payload }}'
      url: /post
